#!/usr/bin/env python

import sys

import rssdler
#pickle looks for these in __main__
from rssdler import SaveInfo, FailedItem, DownloadItemConfig 

if __name__ == '__main__': rssdler._main(sys.argv)
